Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,9 +72,13 @@ jobs:
               echo "No old process running."
             fi
             echo "🔹 Starting new process with prod profile..."
-            cd /home/${{ secrets.SERVER_USER }}/hes-app
-            nohup /usr/bin/java \
-              -Dspring.profiles.active=prod \
+            cd /home/${{ secrets.SERVER_USER }}/hes-app || { echo "Directory not found"; exit 1; }
+            if [[ ! -f hes-0.0.1-SNAPSHOT.jar ]]; then
+                echo "JAR file not found!"
+                exit 1
+            fi
+            nohup  \
+              java -Dspring.profiles.active=prod \
               -DDB_USERNAME=${{ secrets.DB_USERNAME }} \
               -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} \
               -DSPRING_SECURITY_USER=${{ secrets.SPRING_SECURITY_USER }} \
